<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-04T19:39:58 ICT" name="TestSuite" finished-at="2023-10-04T19:40:01 ICT" duration-ms="2994">
    <groups>
    </groups>
    <test started-at="2023-10-04T19:39:58 ICT" name="LoginTest" finished-at="2023-10-04T19:40:01 ICT" duration-ms="2994">
      <class name="com.automation.testcase.TC_LoginTest">
        <test-method is-config="true" signature="initDriverInstance()[pri:0, instance:com.automation.testcase.TC_LoginTest@33bc72d1]" started-at="2023-10-04T19:39:58 ICT" name="initDriverInstance" finished-at="2023-10-04T19:39:59 ICT" duration-ms="1712" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriverInstance -->
        <test-method signature="TC01_LoginFirstAccount(java.lang.String,java.lang.String)[pri:0, instance:com.automation.testcase.TC_LoginTest@33bc72d1]" started-at="2023-10-04T19:40:00 ICT" name="TC01_LoginFirstAccount" data-provider="Excel" finished-at="2023-10-04T19:40:00 ICT" duration-ms="0" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:57)
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:157)
at org.testng.internal.Parameters.handleParameters(Parameters.java:803)
at org.testng.internal.Parameters.handleParameters(Parameters.java:728)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:911)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
at com.automation.testcase.TC_LoginTest.testDataGenerator(TC_LoginTest.java:76)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:53)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_LoginFirstAccount -->
        <test-method is-config="true" signature="closeDriverInstance()[pri:0, instance:com.automation.testcase.TC_LoginTest@33bc72d1]" started-at="2023-10-04T19:40:00 ICT" name="closeDriverInstance" finished-at="2023-10-04T19:40:01 ICT" duration-ms="619" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriverInstance -->
      </class> <!-- com.automation.testcase.TC_LoginTest -->
    </test> <!-- LoginTest -->
  </suite> <!-- TestSuite -->
</testng-results>
